env:
  - PROJECT=key_value

sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

service:
  - mysql

addons:
  apt:
    packages:
    - nginx

cache:
  directories:
  - $HOME/.drush/cache/download

before_cache:
  - rm -rf $HOME/www/modules/*
  - find $HOME/www/sites/*/settings.php -exec rm -f {} \;
  - find $HOME/www/sites/*/files/* -exec rm -rf {} \;

before_install:
  - cp $TRAVIS_BUILD_DIR/.travis/php.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/
  - cp $TRAVIS_BUILD_DIR/.travis/php-fpm.conf ~/.phpenv/versions/$(phpenv version-name)/etc/
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - nginx -c $TRAVIS_BUILD_DIR/.travis/nginx.conf
  - wget -P ~/ https://github.com/drush-ops/drush/releases/download/8.0.0-rc3/drush.phar && chmod +x ~/drush.phar
  - php ~/drush.phar make $TRAVIS_BUILD_DIR/.travis/drupal.make.yml $HOME/www
  - php ~/drush.phar --root=$HOME/www --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing

install:
  - ln -s $TRAVIS_BUILD_DIR ~/www/modules/$PROJECT

script:
  - cd ~/www && php ./core/scripts/run-tests.sh --verbose --keep-results --color --concurrency 4 --php `which php` --sqlite /tmp/test.sqlite --url http://localhost:8080 "$PROJECT" | tee /tmp/test.log ; export STATUS_SCRIPT=${PIPESTATUS[0]}
  # Workaround so that we exit with the correct status.
  - STATUS_LOG=$(! egrep -i "([0-9]+ fails)|([0-9]+ exceptions)|(PHP Fatal error)|(FATAL)" /tmp/test.log > /dev/null)$?
  - test $STATUS_SCRIPT -eq 0 && test $STATUS_LOG -eq 0
